DROP TABLE IF EXISTS LIKES  ;
DROP TABLE IF EXISTS FRIENDS ;
DROP TABLE IF EXISTS USERS ;
DROP TABLE IF EXISTS FILMS_GENRE;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS FILMS;
DROP TABLE IF EXISTS MPA;

-- DELETE FROM USERS WHERE ID > 0;
-- DELETE FROM FRIENDS WHERE USER_ID > 0;
-- DELETE FROM FILMS WHERE ID > 0;
-- DELETE FROM LIKES WHERE FILM_ID > 0;
-- DELETE FROM FILMS_GENRE WHERE FILM_ID > 0;
