DROP TABLE IF EXISTS LIKES  ;
DROP TABLE IF EXISTS FRIENDS ;
DROP TABLE IF EXISTS USERS ;
DROP TABLE IF EXISTS FILMS_GENRE;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS FILMS;
DROP TABLE IF EXISTS MPA;
